//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int ID { get; set; }
        public string GroupName { get; set; }
        public string Privacy { get; set; }
        public string Description { get; set; }
        public string Session { get; set; }
        public string Faculty { get; set; }
        public string Creator { get; set; }
    }
}
